// Украинский оверлей для Univer. В пакете нет uk-UA, поэтому берём ru-RU как базу
// и накладываем сверху перевод самой видимой части UI (лента, тулбар, меню, диалоги).
// Всё, что не переведено здесь, остаётся на русском (ближайшая кириллица).
export const univerUkOverlay = {
  ui: {
    ribbon: {
      start: "Головна",
      startDesc: "Ініціалізація таблиці та основні параметри.",
      insert: "Вставлення",
      insertDesc: "Вставлення рядків, стовпців, графіків та інших елементів.",
      formulas: "Формули",
      formulasDesc: "Функції та формули для обчислень.",
      data: "Дані",
      dataDesc: "Керування даними: імпорт, сортування, фільтрація.",
      view: "Вигляд",
      viewDesc: "Режими відображення та їх налаштування.",
      others: "Інше",
      othersDesc: "Інші функції та налаштування.",
      more: "Більше",
    },
    zoom_slider: { resetTo: "Скинути до" },
  },
  "sheets-formula-ui": {
    insert: { tooltip: "Функції", common: "Часто вживані функції" },
    functionType: {
      financial: "Фінансові",
      date: "Дата й час",
      math: "Математика й тригонометрія",
      statistical: "Статистичні",
      lookup: "Пошук і посилання",
      database: "База даних",
      text: "Текстові",
      logical: "Логічні",
      information: "Інформаційні",
      engineering: "Інженерні",
      cube: "Куб",
      compatibility: "Сумісність",
      web: "Веб",
      array: "Масив",
      univer: "Універсальні",
      user: "Користувацькі",
    },
  },
  "sheets-ui": {
    toolbar: {
      undo: "Скасувати",
      redo: "Повторити",
      formatPainter: "Копіювати формат",
      font: "Шрифт",
      fontSize: "Розмір шрифту",
      fontSizeIncrease: "Збільшити шрифт",
      fontSizeDecrease: "Зменшити шрифт",
      bold: "Жирний",
      italic: "Курсив",
      strikethrough: "Закреслений",
      subscript: "Нижній індекс",
      superscript: "Верхній індекс",
      underline: "Підкреслений",
      textColor: { main: "Колір тексту", right: "Обрати колір" },
      resetColor: "Скинути",
      fillColor: { main: "Колір заливки", right: "Обрати колір" },
      border: { main: "Межа", right: "Стиль межі" },
      mergeCell: { main: "Об’єднати клітинки", right: "Тип об’єднання" },
      horizontalAlignMode: { main: "Горизонтальне вирівнювання", right: "Вирівнювання" },
      verticalAlignMode: { main: "Вертикальне вирівнювання", right: "Вирівнювання" },
      textWrapMode: { main: "Перенесення тексту", right: "Режим перенесення" },
      textRotateMode: { main: "Поворот тексту", right: "Режим повороту" },
      more: "Більше",
      toggleGridlines: "Показати/сховати сітку",
      textToNumber: "Перетворити текст на число",
    },
    rightClick: {
      copy: "Копіювати",
      cut: "Вирізати",
      paste: "Вставити",
      copySpecial: "Копіювати спеціально",
      pasteSpecial: "Спеціальне вставлення",
      pasteValue: "Вставити значення",
      pasteFormat: "Вставити формат",
      insert: "Вставити",
      insertRow: "Вставити рядок",
      insertRowBefore: "Вставити рядок вище",
      insertColumn: "Вставити стовпець",
      insertColumnBefore: "Вставити стовпець ліворуч",
      delete: "Видалити",
      deleteCell: "Видалити клітинку",
      insertCell: "Вставити клітинку",
      deleteSelected: "Видалити вибране",
      hide: "Сховати",
      hideSelected: "Сховати вибране",
      showHide: "Показати сховане",
      deleteSelectedRow: "Видалити вибраний рядок",
      deleteSelectedColumn: "Видалити вибраний стовпець",
      rowHeight: "Висота рядка",
      columnWidth: "Ширина стовпця",
      moveLeft: "Перемістити ліворуч",
      moveUp: "Перемістити вгору",
      moveRight: "Перемістити праворуч",
      moveDown: "Перемістити вниз",
      add: "Додати",
      row: "Рядок",
      column: "Стовпець",
      confirm: "Підтвердити",
      clearSelection: "Очистити",
      clearContent: "Очистити вміст",
      clearFormat: "Очистити формат",
      clearAll: "Очистити все",
      fitContent: "Підігнати під дані",
      freeze: "Закріпити",
      freezeFirstCol: "Закріпити перший стовпець",
      freezeFirstRow: "Закріпити перший рядок",
      cancelFreeze: "Скасувати закріплення",
      textToNumber: "Перетворити текст на число",
    },
  },
  design: {
    Confirm: { cancel: "Скасувати", confirm: "OK" },
    CascaderList: { empty: "Немає" },
    Select: { empty: "Немає" },
    Calendar: {
      weekDays: ["Нд", "Пн", "Вт", "Ср", "Чт", "Пт", "Сб"],
      months: [
        "Січень", "Лютий", "Березень", "Квітень", "Травень", "Червень",
        "Липень", "Серпень", "Вересень", "Жовтень", "Листопад", "Грудень",
      ],
    },
    ColorPicker: { more: "Більше кольорів", cancel: "Скасувати", confirm: "OK" },
  },
};
